name: uruDendro
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
      - numpy == 1.19.5
      - matplotlib == 3.3.4
      - opencv-python == 4.4.0.16
      - pandas == 1.1.5
      - shapely == 1.7.0
      - pillow == 8.4.0
