name: uruDendro
channels:
  - defaults
dependencies:
  - python=3.12.4
  - pip
  - pip:
        - beautifulsoup4==4.12.3
        - certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1720457958366/work/certifi
        - charset-normalizer==3.3.2
        - coloredlogs==15.0.1
        - contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1712429918028/work
        - customtkinter==5.2.2
        - cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1696677705766/work
        - darkdetect==0.8.0
        - dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
        - evdev==1.7.1
        - filelock==3.15.4
        - flatbuffers==24.3.25
        - fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1720359030700/work
        - gdown==5.2.0
        - humanfriendly==10.0
        - idna==3.7
        - imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1719236146989/work
        - imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1719234999090/work
        - imgviz==1.7.5
        - importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1721856510709/work
        - joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1714665484399/work
        - kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1695379925569/work
        - labelme==5.5.0
        - lazy_loader @ file:///home/conda/feedstock_root/build_artifacts/lazy_loader_1712342969017/work
        - matplotlib==3.9.1
        - mpmath==1.3.0
        - munkres==1.1.4
        - natsort==8.4.0
        - networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1712540363324/work
        - numpy==1.26.4
        - onnxruntime==1.18.1
        - opencv-python-headless==4.10.0.84
        - packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
        - pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1715897630316/work
        - pathlib==1.0.1
        - pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1719903548521/work
        - ply @ file:///home/conda/feedstock_root/build_artifacts/ply_1712242996588/work
        - protobuf==5.27.2
        - pynput==1.7.7
        - pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1709721012883/work
        - PyQt5==5.15.9
        - PyQt5-sip==12.12.2
        - PySocks==1.7.1
        - python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
        - python-xlib==0.33
        - pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
        - PyWavelets==1.6.0
        - PyYAML==6.0.1
        - QtPy==2.4.1
        - requests==2.32.3
        - scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1719499445894/work/dist/scikit_image-0.24.0-cp312-cp312-linux_x86_64.whl#sha256=f2c98aa19c004a87d041c2e31ba2f03de6e7464dc8ed338cb03f67328cd3c81d
        - scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1719998091999/work/dist/scikit_learn-1.5.1-cp312-cp312-linux_x86_64.whl#sha256=67792e358aac20df1b7a20c4cc9f00269449d382e15c1d403bf76d77b7de0a03
        - scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1720323012716/work/dist/scipy-1.14.0-cp312-cp312-linux_x86_64.whl#sha256=6b6734654444e3e1050c9f567e3c32f0fdb69d833d146d48adcf3ab505cc0cc4
        - setuptools==71.0.4
        - Shapely==1.7.0
        - sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1697300425834/work
        - six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
        - soupsieve==2.5
        - sympy==1.13.1
        - termcolor==2.4.0
        - threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1714400101435/work
        - tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1721813262608/work
        - toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
        - tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
        - tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1717722879218/work
        - tqdm==4.66.4
        - tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1707747584337/work
        - urllib3==2.2.2
        - wheel==0.43.0
        - zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1718013267051/work
